"""添加use_hybrid字段

Revision ID: 0040e13408e4
Revises: 7510edef5116
Create Date: 2026-04-30 18:42:07.178041

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040e13408e4'
down_revision: Union[str, None] = '7510edef5116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('use_hybrid', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('processing_stage', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    op.drop_index('idx_tasks_completed_created', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_index('idx_tasks_filename', table_name='tasks')
    op.drop_index('idx_tasks_layout_mode', table_name='tasks')
    op.drop_index('idx_tasks_status_created', table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_tasks_layout_mode', 'tasks', ['layout_mode'], unique=False)
    op.create_index('idx_tasks_filename', 'tasks', ['input_filename'], unique=False)
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_completed_created', 'tasks', ['completed_at', 'created_at'], unique=False)
    op.drop_column('tasks', 'progress')
    op.drop_column('tasks', 'processing_stage')
    op.drop_column('tasks', 'use_hybrid')
    # ### end Alembic commands ###
