"""添加enable_llm字段

Revision ID: 4053cc466253
Revises: 6dabad8f430a
Create Date: 2026-03-29 10:30:44.578161

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4053cc466253'
down_revision: Union[str, None] = '6dabad8f430a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('enable_llm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'enable_llm')
    # ### end Alembic commands ###
